def build_radiojove_edr_sp_skt,
	"""
	
	"""
	
	nchan = 2
	nfreq = 200
	obsty = 'aj4co'
	instr = 'dsp'
	dtype = 'edr'
	descr = 'sp{:1d}_{:03d}'.format(nchan,nfreq)
	odate = '00000000'
	cdf_vers = '00'
	skt_vers = '00'
	dat_vers = '05'
	sft_vers = '00'
	logic_src = 'radiojove_{}_{}_{}_{}'.format(obsty,instr,dtype,descr)
	instr_typ = 'Spectrogram Receiver'
	file_name = '{}_{}_v{}'.format(logic_src,odate,cdf_vers)
	
	f = open(file_name+'.skt','w')
		
	f.write('! Skeleton table for the "{:s}" CDF.\n'.format(file_name))
	f.write('! Generated: {:s}\n'.format(datetime.datetime.now().strftime("%A, %d-%b-%Y %H:%M:%S")))
	f.write('! CDF created/modified by CDF V3.6.0\n')
	f.write('! Skeleton table created by CDF V3.6.2_1\n')
	f.write('\n')
	f.write('#header\n')
	f.write('\n')
	f.write('                       CDF NAME: {:s}\n'.format(file_name))
	f.write('                  DATA ENCODING: PPC\n')
	f.write('                       MAJORITY: COLUMN\n')
	f.write('                         FORMAT: SINGLE\n')
	f.write('\n')
	f.write('! Variables  G.Attributes  V.Attributes  Records  Dims  Sizes\n')
	f.write('! ---------  ------------  ------------  -------  ----  -----\n')
	f.write('     0/4          54            37         0/z      0\n')
	f.write('! CDF_COMPRESSION: None\n')
	f.write('! (Valid compression: None, GZIP.1-9, RLE.0, HUFF.0, AHUFF.0)\n')
	f.write('! CDF_CHECKSUM: MD5\n')
	f.write('! (Valid checksum: None, MD5)\n')
	f.write('\n')
	f.write('\n')
	f.write('#GLOBALattributes\n')
	f.write('\n')
	f.write('! Attribute         Entry       Data\n')
	f.write('! Name              Number      Type       Value\n')
	f.write('! ---------         ------      ----       -----\n')
	f.write('\n')
	f.write('  "Project"             1:    CDF_CHAR     { "RadioJOVE" } .\n')
	f.write('\n')
	f.write('  "Discipline"          1:    CDF_CHAR     { "Space " -\n')
	f.write('                                             "Physics>Magnetospheric " -\n')
	f.write('                                             "Science" } .\n')
	f.write('\n')
	f.write('  "Data_type"           1:    CDF_CHAR     { "EDR" } .\n')
	f.write('\n')
	f.write('  "Descriptor"          1:    CDF_CHAR     { "{:s}" } .\n'.format(descr))
	f.write('\n')
	f.write('  "Data_version"        1:    CDF_CHAR     { "{:s}" } .\n'.format(dat_v))
	f.write('\n')
	f.write('  "Instrument_type"     1:    CDF_CHAR     { "{:s}" } .\n'.format(instr_typ))
	f.write('\n')
	f.write('  "Logical_file_id"     1:    CDF_CHAR     { "{:s}" } .\n'.format(file_name))
	f.write('\n')
	f.write('  "Logical_source"      1:    CDF_CHAR     { "{:s}" } .\n'.format(logic_src))
	f.write('\n')
	f.write('  "Logical_source_description"\n')
	f.write('                        1:    CDF_CHAR     { "RadioJOVE Dual Channel " -\n')
	f.write('                                             "Spectrograph" } .\n')
	f.write('\n')
	f.write('  "File_naming_convention"\n')
	f.write('                        1:    CDF_CHAR     { "source_descriptor_yyyyMM" -\n')
	f.write('                                             "ddH_Vvv" } .\n')
	f.write('\n')
	f.write('  "Mission_group"       1:    CDF_CHAR     { "RadioJOVE" } .\n')
	f.write('\n')
	f.write('  "PI_name"             1:    CDF_CHAR     { "RadioJOVE Project" } .\n')
	f.write('\n')
	f.write('  "PI_affiliation"      1:    CDF_CHAR     { "RadioJOVE" } .\n')
	f.write('\n')
	f.write('  "Source_name"         1:    CDF_CHAR     { "RadioJOVE" } .\n')
	f.write('\n')
	f.write('  "TEXT"                1:    CDF_CHAR     { "RadioJOVE Project data." } .\n')
	f.write('\n')
	f.write('  "Generated_by"        1:    CDF_CHAR     { "SkyPipe" }\n')
	f.write('                        2:    CDF_CHAR     { "RadioJOVE" }\n')
	f.write('                        3:    CDF_CHAR     { "VOPDC" } .\n')
	f.write('\n')
	f.write('  "Generation_date" .\n')
	f.write('\n')
	f.write('  "LINK_TEXT"           1:    CDF_CHAR     { "Radio-SkyPipe Software " -\n')
	f.write('                                             "webpage" }\n')
	f.write('                        2:    CDF_CHAR     { "RadioJOVE webpage" }\n')
	f.write('                        3:    CDF_CHAR     { "VOParis Data Centre webpage" } .\n')
	f.write('\n')
	f.write('  "LINK_TITLE"          1:    CDF_CHAR     { "Radio-SkyPipe Software" }\n')
	f.write('                        2:    CDF_CHAR     { "RadioJOVE" }\n')
	f.write('                        3:    CDF_CHAR     { "VOParis Data Centre" } .\n')
	f.write('\n')
	f.write('  "HTTP_LINK"           1:    CDF_CHAR     { "http://www.radiosky.com/sk" -\n')
	f.write('                                             "ypipeishere.html" }\n')
	f.write('                        2:    CDF_CHAR     { "http://radiojove.gsfc.nasa" -\n')
	f.write('                                             ".gov" }\n')
	f.write('                        3:    CDF_CHAR     { "http://voparis-europlanet." -\n')
	f.write('                                             "obspm.fr" } .\n')
	f.write('\n')
	f.write('  "MODS" .\n')
	f.write('\n')
	f.write('  "Parents" .\n')
	f.write('\n')
	f.write('  "Rules_of_use" .\n')
	f.write('\n')
	f.write('  "Skeleton_version"\n')
	f.write('                        1:    CDF_CHAR     { "{:s}" } .\n'.format(skt_vers))
	f.write('\n')
	f.write('  "Software_version"\n')
	f.write('                        1:    CDF_CHAR     { "{:s}" } .\n'.format(sft_vers))
	f.write('\n')
	f.write('  "Time_resolution" .\n')
	f.write('\n')
	f.write('  "Acknowledgement" .\n')
	f.write('\n')
	f.write('  "ADID_ref" .\n')
	f.write('\n')
	f.write('  "Validate" .\n')
	f.write('\n')
	f.write('  "PDS_Observation_start_time"\n')
	f.write('                        1:    CDF_CHAR     { "0000-01-01T00:00:00.000Z" } .\n')
	f.write('\n')
	f.write('  "PDS_Observation_stop_time"\n')
	f.write('                        1:    CDF_CHAR     { "0000-01-01T00:00:00.000Z" } .\n')
	f.write('\n')
	f.write('  "PDS_Observation_target"\n')
	f.write('                        1:    CDF_CHAR     { "Jupiter" } .\n')
	f.write('\n')
	f.write('  "PDS_Observation_type"\n')
	f.write('                        1:    CDF_CHAR     { "Waves" } .\n')
	f.write('\n')
	f.write('  "VESPA_dataproduct_type"\n')
	f.write('                        1:    CDF_CHAR     { "DS>Dynamic Spectra" } .\n')
	f.write('\n')
	f.write('  "VESPA_target_class"  1:    CDF_CHAR     { "planet" } .\n')
	f.write('\n')
	f.write('  "VESPA_target_region" 1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "VESPA_target_element"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "VESPA_time_min"      1:    CDF_REAL8    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_time_max"      1:    CDF_REAL8    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_time_sampling_min"\n')
	f.write('                        1:    CDF_REAL4    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_time_sampling_max"\n')
	f.write('                        1:    CDF_REAL4    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_spectral_range_min"\n')
	f.write('                        1:    CDF_REAL4    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_spectral_range_max"\n')
	f.write('                        1:    CDF_REAL4    { 0.0 } .\n')
	f.write('\n')
	f.write('  "VESPA_instrument_host_name"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "VESPA_instrument_name"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "VESPA_measurement_type"\n')
	f.write('                        1:    CDF_CHAR     { "phys.flux;em.radio" } .\n')
	f.write('\n')
	f.write('  "VESPA_access_format" 1:    CDF_CHAR     { "cdf" } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_observer_name"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_observatory_location"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_observatory_latitude"\n')
	f.write('                        1:    CDF_REAL8    { 0.0 } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_observatory_longitude"\n')
	f.write('                        1:    CDF_REAL8    { 0.0 } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_dipole_orientation_angle"\n')
	for i in arange(nchan):
		f.write('                       {:d}:    CDF_REAL8    { 0.0 }'.format(i))
		if i.last():
			f.write(' .\n')
		else:
			f.write('\n')
	f.write('                        \n')
	f.write('  "RadioJOVE_original_filename"\n')
	f.write('                        1:    CDF_CHAR     { " " } .\n')
	f.write('\n')
	f.write('  "RadioJOVE_n_channel" 1:    CDF_BYTE     { 0 } .\n')
	f.write('\n')
	f.write('\n')
	f.write('#VARIABLEattributes\n')
	f.write('\n')
	f.write('  "CATDESC"\n')
	f.write('  "DEPEND_0"\n')
	f.write('  "DEPEND_1"\n')
	f.write('  "DEPEND_2"\n')
	f.write('  "DEPEND_3"\n')
	f.write('  "DICT_KEY"\n')
	f.write('  "DISPLAY_TYPE"\n')
	f.write('  "FIELDNAM"\n')
	f.write('  "FILLVAL"\n')
	f.write('  "FORMAT"\n')
	f.write('  "LABLAXIS"\n')
	f.write('  "LABL_PTR_1"\n')
	f.write('  "LABL_PTR_2"\n')
	f.write('  "LABL_PTR_3"\n')
	f.write('  "UNITS"\n')
	f.write('  "UNIT_PTR"\n')
	f.write('  "VALIDMIN"\n')
	f.write('  "VALIDMAX"\n')
	f.write('  "VAR_TYPE"\n')
	f.write('  "SCALETYP"\n')
	f.write('  "SCAL_PTR"\n')
	f.write('  "VAR_NOTES"\n')
	f.write('  "MONOTON"\n')
	f.write('  "LEAP_SECONDS_INCLUDED"\n')
	f.write('  "RESOLUTION"\n')
	f.write('  "Bin_location"\n')
	f.write('  "TIME_BASE"\n')
	f.write('  "TIME_SCALE"\n')
	f.write('  "REFERENCE_POSITION"\n')
	f.write('  "ABSOLUTE_ERROR"\n')
	f.write('  "RELATIVE_ERROR"\n')
	f.write('  "FORM_PTR"\n')
	f.write('  "DELTA_PLUS_VAR"\n')
	f.write('  "DELTA_MINUS_VAR"\n')
	f.write('  "SCALEMIN"\n')
	f.write('  "SCALEMAX"\n')
	f.write('  "UCD"\n')
	f.write('\n')
	f.write('\n')
	f.write('#variables\n')
	f.write('\n')
	f.write('! No rVariables.\n')
	f.write('\n')
	f.write('\n')
	f.write('#zVariables\n')
	f.write('\n')
	f.write('! Variable          Data      Number                 Record   Dimension\n')
	f.write('! Name              Type     Elements  Dims  Sizes  Variance  Variances\n')
	f.write('! --------          ----     --------  ----  -----  --------  ---------\n')
	f.write('\n')
	f.write('  "Epoch"         CDF_EPOCH16     1       0              T\n')
	f.write('\n')
	f.write('  ! VAR_COMPRESSION: None\n')
	f.write('  ! (Valid compression: None, GZIP.1-9, RLE.0, HUFF.0, AHUFF.0)\n')
	f.write('  ! VAR_SPARSERECORDS: None\n')
	f.write('  ! (Valid sparserecords: None, sRecords.PAD, sRecords.PREV)\n')
	f.write('  ! VAR_PADVALUE: 01-Jan-0000 00:00:00.000.000.000.000\n')
	f.write('\n')
	f.write('  ! Attribute       Data\n')
	f.write('  ! Name            Type       Value\n')
	f.write('  ! --------        ----       -----\n')
	f.write('\n')
	f.write('    "CATDESC"     CDF_CHAR     { "Default time" }\n')
	f.write('    "FIELDNAM"    CDF_CHAR     { "Epoch" }\n')
	f.write('    "FILLVAL"     CDF_EPOCH16   { 31-Dec-9999 23:59:59.999.999.999.999 }\n')
	f.write('    "LABLAXIS"    CDF_CHAR     { "Epoch" }\n')
	f.write('    "UNITS"       CDF_CHAR     { " " }\n')
	f.write('    "VALIDMIN"    CDF_EPOCH16   { 01-Jan-2000 00:00:00.000.000.000.000 }\n')
	f.write('    "VALIDMAX"    CDF_EPOCH16   { 01-Jan-2020 00:00:00.000.000.000.000 }\n')
	f.write('    "VAR_TYPE"    CDF_CHAR     { "support_data" }\n')
	f.write('    "SCALETYP"    CDF_CHAR     { "linear" }\n')
	f.write('    "MONOTON"     CDF_CHAR     { "INCREASE" }\n')
	f.write('    "TIME_BASE"   CDF_CHAR     { "J2000" }\n')
	f.write('    "TIME_SCALE"  CDF_CHAR     { "UTC" }\n')
	f.write('    "REFERENCE_POSITION"\n')
	f.write('                  CDF_CHAR     { "Earth" }\n')
	f.write('    "SCALEMIN"    CDF_EPOCH16   { 01-Jan-0000 00:00:00.000.000.000.000 }\n')
	f.write('    "SCALEMAX"    CDF_EPOCH16   { 01-Jan-0000 00:00:00.000.000.000.000 }\n')
	f.write('    "UCD"         CDF_CHAR     { "time.epoch" } .\n')
	f.write('\n')
	f.write('  ! RV values were not requested.\n')
	f.write('\n')
	f.write('\n')
	f.write('! Variable          Data      Number                 Record   Dimension\n')
	f.write('! Name              Type     Elements  Dims  Sizes  Variance  Variances\n')
	f.write('! --------          ----     --------  ----  -----  --------  ---------\n')
	f.write('\n')
	f.write('  "DATA_1"        CDF_FLOAT      1       1    200       T         T\n')
	f.write('\n')
	f.write('  ! VAR_COMPRESSION: None\n')
	f.write('  ! (Valid compression: None, GZIP.1-9, RLE.0, HUFF.0, AHUFF.0)\n')
	f.write('  ! VAR_SPARSERECORDS: None\n')
	f.write('  ! (Valid sparserecords: None, sRecords.PAD, sRecords.PREV)\n')
	f.write('  ! VAR_PADVALUE: -1.0e+30\n')
	f.write('\n')
	f.write('  ! Attribute       Data\n')
	f.write('  ! Name            Type       Value\n')
	f.write('  ! --------        ----       -----\n')
	f.write('\n')
	f.write('    "CATDESC"     CDF_CHAR     { "Data stream on Channel 1" }\n')
	f.write('    "DEPEND_0"    CDF_CHAR     { "Epoch" }\n')
	f.write('    "DEPEND_1"    CDF_CHAR     { "FREQUENCY" }\n')
	f.write('    "DICT_KEY"    CDF_CHAR     { "electric_field>power" }\n')
	f.write('    "DISPLAY_TYPE"\n')
	f.write('                  CDF_CHAR     { "spectrogram" }\n')
	f.write('    "FIELDNAM"    CDF_CHAR     { "DATA_1" }\n')
	f.write('    "FILLVAL"     CDF_FLOAT    { -1.0e+31 }\n')
	f.write('    "FORMAT"      CDF_CHAR     { "F8.3" }\n')
	f.write('    "LABLAXIS"    CDF_CHAR     { "Power Spectral Density on Channel 1" }\n')
	f.write('    "UNITS"       CDF_CHAR     { " " }\n')
	f.write('    "VALIDMIN"    CDF_FLOAT    { 0.0 }\n')
	f.write('    "VALIDMAX"    CDF_FLOAT    { 5000.0 }\n')
	f.write('    "VAR_TYPE"    CDF_CHAR     { "data" }\n')
	f.write('    "SCALETYP"    CDF_CHAR     { "lin" }\n')
	f.write('    "SCALEMIN"    CDF_FLOAT    { 0.0 }\n')
	f.write('    "SCALEMAX"    CDF_FLOAT    { 5000.0 }\n')
	f.write('    "UCD"         CDF_CHAR     { "phys.flux;em.radio" } .\n')
	f.write('\n')
	f.write('  ! RV values were not requested.\n')
	f.write('\n')
	f.write('\n')
	f.write('! Variable          Data      Number                 Record   Dimension\n')
	f.write('! Name              Type     Elements  Dims  Sizes  Variance  Variances\n')
	f.write('! --------          ----     --------  ----  -----  --------  ---------\n')
	f.write('\n')
	f.write('  "DATA_2"        CDF_FLOAT      1       1    200       T         T\n')
	f.write('\n')
	f.write('  ! VAR_COMPRESSION: None\n')
	f.write('  ! (Valid compression: None, GZIP.1-9, RLE.0, HUFF.0, AHUFF.0)\n')
	f.write('  ! VAR_SPARSERECORDS: None\n')
	f.write('  ! (Valid sparserecords: None, sRecords.PAD, sRecords.PREV)\n')
	f.write('  ! VAR_PADVALUE: -1.0e+30\n')
	f.write('\n')
	f.write('  ! Attribute       Data\n')
	f.write('  ! Name            Type       Value\n')
	f.write('  ! --------        ----       -----\n')
	f.write('\n')
	f.write('    "CATDESC"     CDF_CHAR     { "Data stream on Channel 2" }\n')
	f.write('    "DEPEND_0"    CDF_CHAR     { "Epoch" }\n')
	f.write('    "DEPEND_1"    CDF_CHAR     { "FREQUENCY" }\n')
	f.write('    "DICT_KEY"    CDF_CHAR     { "electric_field>power" }\n')
	f.write('    "DISPLAY_TYPE"\n')
	f.write('                  CDF_CHAR     { "spectrogram" }\n')
	f.write('    "FIELDNAM"    CDF_CHAR     { "DATA_2" }\n')
	f.write('    "FILLVAL"     CDF_FLOAT    { -1.0e+31 }\n')
	f.write('    "FORMAT"      CDF_CHAR     { "F8.3" }\n')
	f.write('    "LABLAXIS"    CDF_CHAR     { "Power Spectral Density on Channel 2" }\n')
	f.write('    "UNITS"       CDF_CHAR     { " " }\n')
	f.write('    "VALIDMIN"    CDF_FLOAT    { 0.0 }\n')
	f.write('    "VALIDMAX"    CDF_FLOAT    { 5000.0 }\n')
	f.write('    "VAR_TYPE"    CDF_CHAR     { "data" }\n')
	f.write('    "SCALETYP"    CDF_CHAR     { "lin" }\n')
	f.write('    "SCALEMIN"    CDF_FLOAT    { 0.0 }\n')
	f.write('    "SCALEMAX"    CDF_FLOAT    { 5000.0 }\n')
	f.write('    "UCD"         CDF_CHAR     { "phys.flux;em.radio" } .\n')
	f.write('\n')
	f.write('  ! RV values were not requested.\n')
	f.write('\n')
	f.write('\n')
	f.write('! Variable          Data      Number                 Record   Dimension\n')
	f.write('! Name              Type     Elements  Dims  Sizes  Variance  Variances\n')
	f.write('! --------          ----     --------  ----  -----  --------  ---------\n')
	f.write('\n')
	f.write('  "FREQUENCY"     CDF_FLOAT      1       1    200       F         T\n')
	f.write('\n')
	f.write('  ! VAR_COMPRESSION: None\n')
	f.write('  ! (Valid compression: None, GZIP.1-9, RLE.0, HUFF.0, AHUFF.0)\n')
	f.write('  ! VAR_SPARSERECORDS: None\n')
	f.write('  ! (Valid sparserecords: None, sRecords.PAD, sRecords.PREV)\n')
	f.write('  ! VAR_PADVALUE: -1.0e+30\n')
	f.write('\n')
	f.write('  ! Attribute       Data\n')
	f.write('  ! Name            Type       Value\n')
	f.write('  ! --------        ----       -----\n')
	f.write('\n')
	f.write('    "CATDESC"     CDF_CHAR     { "Frequency value" }\n')
	f.write('    "DICT_KEY"    CDF_CHAR     { "support_data" }\n')
	f.write('    "DISPLAY_TYPE"\n')
	f.write('                  CDF_CHAR     { "time_series" }\n')
	f.write('    "FIELDNAM"    CDF_CHAR     { "FREQUENCY" }\n')
	f.write('    "FILLVAL"     CDF_FLOAT    { -1.0e+31 }\n')
	f.write('    "FORMAT"      CDF_CHAR     { "F15.3" }\n')
	f.write('    "LABLAXIS"    CDF_CHAR     { "Frequency" }\n')
	f.write('    "UNITS"       CDF_CHAR     { "Hz" }\n')
	f.write('    "VALIDMIN"    CDF_FLOAT    { 0.0 }\n')
	f.write('    "VALIDMAX"    CDF_FLOAT    { 1.0e+08 }\n')
	f.write('    "VAR_TYPE"    CDF_CHAR     { "support_data" }\n')
	f.write('    "SCALETYP"    CDF_CHAR     { "log" }\n')
	f.write('    "SCALEMIN"    CDF_FLOAT    { 1.0e+07 }\n')
	f.write('    "SCALEMAX"    CDF_FLOAT    { 4.0e+07 }\n')
	f.write('    "UCD"         CDF_CHAR     { "em.freq" } .\n')
	f.write('\n')
	f.write('  ! RV values were not requested.\n')
	f.write('\n')
	f.write('\n')
	f.write('#end\n')
	
	